exp:
  name: hecto_image_classification
  model_name: convnext_base_in22k
  seed: 42
  val_size: 0.2
  embedding_dim: 2048
  n_folds: 5

hp:
  img_size: 448
  batch_size: 32
  epochs: 30
  learning_rate: 0.0001
  cpu_count: 16
  optimizer: AdamW
  optimizer_params:
    lr: 0.0001
    weight_decay: 0.00001
    betas: [0.9, 0.999]
  scheduler: CosineAnnealingLR
  scheduler_params:
    T_max: 30
  criterion: CrossEntropyLoss
  criterion_params: {}
  use_swa: true
  swa_start: 20
  swa_freq: 1
  swa_lr: 0.0001
  use_mixup: false
  use_cutmix: true
  
mf:
  mlflow_tracking_uri: https://6m9uma7tvgsttm-5000.proxy.runpod.net

ensemble:
  fold_weighting: "performance"
  aggregation_method: "weighted_average"
